project_id = "swnxpnfeiowpjmkvkejh"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[functions.send-sms-verification]
verify_jwt = false